
version: 2
jobs:
  build:
  machine: true
    docker:
      - image: wbuchwalter/testrpc
     
    steps:
    
      - checkout
      - run:
      docker build -t wbuchwalter/testrpc
      docker push wbuchwalter/testrpc
      ddocker run --rm -d --name testrpc -p 8545 desmart/testrpc:latest
      docker run --rm -v "${PWD}:/usr/src/app" --link testrpc -e "RPC_HOST=testrpc" desmart/truffle:latest test
      
    
