
version: 2
jobs:
  build:
    docker:
      - image: dwbuchwalter/testrpc
    steps:
      - checkout
      - run:
         command: docker run -it -v $(pwd):/app ethereum/client-go --datadir /app/geth/data init /app/genesis.json
      
        command: docker run -d -p 8545:8545 -v $(pwd):/app ethereum/client-go --datadir /app/geth/data --networkid 20170123 --rpc --rpcaddr "0.0.0.0" --verbosity 5
      
         command: node scripts/waitForEthSync.js
      
        command: truffle migrate
