version: 2
jobs:
  build:
    docker:
      - image: circleci/node
      - image: wbuchwalter/testrpc
      - image: circleci/postgres
    steps:
      - checkout
     # - run: sudo nohup docker daemon -H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock &
      - run:
            commands: 
            - sudo nohup docker daemon -H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock &
            - sudo docker run -it -v $(pwd):/app ethereum/client-go --datadir /app/geth/data init /app/genesis.json
      
            
