version: 2
jobs:
  build:
    docker:
      - image: wbuchwalter/testrpc
    steps:
      - checkout
      - run:
            - run:
              name: Install Docker Compose
              command: curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
              
