version: 2
jobs:
  build:
    docker:
      - image: circleci/node
      - image: circleci/postgres
    steps:
      - checkout
      -run: sudo nohup docker daemon -H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock &
            
  
  jobs:          
  test:
    docker:
      
      - image: wbuchwalter/testrpc
      steps:
      - checkout
      - run:
            name: genesis
            command: sudo docker run -it -v $(pwd):/app ethereum/client-go --datadir /app/geth/data init /app/genesis.json
      
            
