
version: 2
jobs:
  build:
    docker:
      - image: dwbuchwalter/testrpc
    steps:
      - checkout
      - run:
         command: docker run -it -v $(pwd):/app ethereum/client-go --datadir /app/geth/data init /app/genesis.json
      - run:
        command: docker run -d -p 8545:8545 -v $(pwd):/app ethereum/client-go --datadir /app/geth/data --networkid 20170123 --rpc --unlock 0x322ba17d251afdb6d84fd288b5aef518208cccb9 --password /app/password --rpcaddr "0.0.0.0" --verbosity 5
      - run:
         command: node scripts/waitForEthSync.js
      - run:
        command: truffle migrate
